name: test multiple actions from same repo

on:
  workflow_dispatch:
    inputs:
      environment:
        type: string
        description: wahuu

  workflow_call:

jobs:
  deploy-with-black-magic:
    runs-on: ubuntu-latest
    environment: test
    steps:
      - name: debug
        run: |
          PROJECT_HOSTNAME=${{fromJson('{"kehitys":"dev", "ennen":"stg", "tuotanto":"prod"}')[inputs.ENVIRONMENT]}}
          echo $PROJECT_HOSTNAME

      - name: print yo
        uses: JuhLehtonen/test-action/printyo@main
      - name: print kek
        uses: JuhLehtonen/test-action/actions/printkek@main

      
        