on:
  push:
    branches:
      - "main"
    
jobs:
  fromJsonTest:
    uses: ./.github/workflows/fromJson.yaml
    
  deploy_test:
    uses: ./.github/workflows/test-hop.yaml

  deploy_staging:
    needs: deploy_test
    uses: ./.github/workflows/test-hop.yaml

  deploy_prod:
    needs: deploy_staging
    uses: ./.github/workflows/environments-test.yaml
