on:
  push:
    branches:
      - "main"
    
jobs:
  deploy_test:
    uses: ./.github/workflows/test-hop.yaml

  deploy_staging:
    needs: deploy_test
    uses: ./.github/workflows/test-hop.yaml

  deploy_prod:
    needs: deploy_staging
    environment: test
    uses: ./.github/workflows/environments-test.yaml